// THIS IS ENTIRELY GENERATED BY COPILOT AS TESTING CODE
// BEWARE
#pragma once
#include <Arduino.h>
#include <due_can.h>

/**
 * UIM5756CAN: Lightweight CAN interface for UIROBOT UIM* drives (e.g., UIM5756CAB).
 *
 * The UIROBOT SDK exposes high-level calls (SdkSetMotorOn, SdkSetPtpMxnA/R, etc.)
 * and a UI_MSG_OBJ { id, cw, dl, data[], ix }. On the wire, these are encoded
 * as CAN frames by the gateway/SDK, but the exact cw codes & CAN IDs are not
 * in the PDF. You only need to define them once in UIM5756CAN.cpp (search for
 * TODO(cw) and TODO(cobid)).
 *
 * Parameter semantics and legal ranges are per "uirSDK3.0 Control System
 * Development Kit" (e.g., PTP Absolute uses Velo [pulse/s], Pa [pulse], NodeID
 * 5..126, accel/decel legal ranges, etc.).  [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
 */
class UIM5756CAN {
public:
  enum Bus : uint8_t { BUS0 = 0, BUS1 = 1 };

  // Motion API (minimal, matching your request)
  bool motorInit(Bus bus, uint32_t bitrateEnum, uint8_t nodeId);
  bool motorinit(Bus bus, uint32_t bitrateEnum, uint8_t nodeId) { // alias
    return motorInit(bus, bitrateEnum, nodeId);
  }

  bool enable();                   // SdkSetMotorOn(..., 1)  [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
  bool disable();                  // SdkSetMotorOn(..., 0)  [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
  bool stopMotors();               // SdkSetStopMxn          [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
  bool eStop() { return stopMotors(); }

  // Position control (PTP)
  bool setPosition(int32_t targetPulse, int32_t speedPulsePerSec);
  bool setRelative(int32_t deltaPulse, int32_t speedPulsePerSec);

  // Jog / velocity
  bool setVelocity(int32_t speedPulsePerSec);  // SdkSetJogMxn       [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
  bool beginMotion();                           // SdkSetBeginMxn     [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
  bool beginMotionAt(uint32_t timeUs);          // SdkSetBeginMxnTime [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)

  // Tuning (static/dynamic params)
  bool setAcceleration(uint32_t val);  // 1..65,000,000 (pps^2) or 1..60,000 ms per mode  [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
  bool setDeceleration(uint32_t val);  // same range                                   [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
  bool setOrigin();                    // zero position                                [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)

  // Telemetry
  bool readMotionStatus(uint16_t &statusBits, int32_t &velo, int32_t &pr, int32_t &pa);
  bool readPtpAbsolute(int &velo, int &pa);  // SdkGetPtpMxnA  [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)
  bool readPtpRelative(int &velo, int &pr);  // SdkGetPtpMxnR  [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)

  // Debug & polling
  void setDebug(Stream *s) { _dbg = s; }
  void poll(); // read and print any unsolicited frames (notifications, etc.) [1](https://emailwsu-my.sharepoint.com/personal/sage_ford_wsu_edu/Documents/Microsoft%20Copilot%20Chat%20Files/Manual_uirSDK3%20V4.7.pdf)

private:
  // CAN core
  CANRaw*   _can = nullptr;
  Bus       _bus = BUS0;
  uint8_t   _nodeId = 5;

  // Arbitration IDs for this node (fill policy in cpp)
  uint32_t  _txId = 0;
  uint32_t  _rxId = 0;

  Stream*   _dbg = nullptr;

  // --- UIROBOT message helpers ---
  // Packs one logical command (cw + ix + payload) into one or more CAN frames as required by your device.
  // The PDF shows UI_MSG_OBJ { id, cw, dl, data[], ix }, but doesn't show the on-wire segmentation.
  // In practice many drives accept a single-frame command (<=8 bytes). We expose a "sendUI" that you
  // can adapt to your device's frame layout once cw & IDs are known.
  bool sendUI_(uint8_t cw, uint8_t ix, const void* payload, uint8_t len, uint32_t timeoutMs);
  bool recvUI_(uint8_t expectCw, uint8_t expectIx, void* buf, uint8_t &lenOut, uint32_t timeoutMs);

  // Low-level CAN I/O
  bool sendFrame_(uint32_t id, const uint8_t* data, uint8_t len);
  bool readFrameBlocking_(uint32_t idFilter, uint8_t* data, uint8_t &len, uint32_t timeoutMs);

  // Compute IDs for this node (policy hook)
  void computeCobIds_(uint8_t nodeId);
};